# -*- coding: utf-8 -*-
"""IF100 - THE2 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12--H-xOgVYWo0tu1JfmjSgFT1Pv7mC8a
"""

dtb = input("Please enter the database: ")
usr = input("Please enter the username: ")
database = dtb.rsplit(",") # a list with each element including the encrypted username:type(s):follower count:following count
usrs = []
usrs = [i.rsplit(":") for i in database]
usernames = [i[0] for i in usrs]
mid = len(usr)//2
encrypted = usr[mid:] + usr[mid-1].lower() + usr[:mid]
if encrypted in usernames:
  a = usernames.index(encrypted)
  follower = int(usrs[a][2])
  following = int(usrs[a][3])
  ratio = following/follower
  if ratio <10:
    ctgrs = [i[1] for i in usrs]
    categories = ctgrs[a]
    categories_final = categories.split("-")
    toa = input("Please enter the type you are interested in: ")
    toa_list = toa.split("-")
    check = all(i in categories_final for i in toa_list)
    if check == True:
      print("It is safe to accept the following request of ", usr,".", sep="")
    else:
      print("Interests do not match with " ,usr, ".", sep="")
  else:
    print("There is a high chance that", usr ,"may be a bot!")
else:
  print("Username does not exist!")