# -*- coding: utf-8 -*-
"""IF100 Take-Home Exam 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gRAbaJ0o0FIveKv_yuJM3u2ktxec5odM
"""

tom_kg = float(input("Please enter the amount of tomatoes (in kg) that you have: "))
speed_ks = float(input("Please enter the boiling speed (rate at which a kg of tomato boiled in a second (kg/sec)): "))
can_liters = float(input("Please enter the volume of a can: "))
#1 liter of can is filled with 1 kg of sauce
pulp_kg = tom_kg/5
leftovers_kg = pulp_kg % can_liters
time_sec = tom_kg/speed_ks
time_h = (time_sec - time_sec%3600)/3600
time_m = ((time_sec - time_h*3600) - (time_sec - time_h*3600)%60)/60
time_s = time_sec - time_h*3600 - time_m*60
can_numbers = pulp_kg // can_liters
cost = leftovers_kg*20 #cost is 0.02tl/gram thus 20tl/kilogram
cost = "{:.2f}".format(cost)
leftovers_kg = "{:.2f}".format(leftovers_kg)
time_s = "{:.2f}".format(time_s)
time_h = int(time_h)
time_m = int(time_m)
can_numbers = int(can_numbers)
print(can_numbers, "number(s) of can is produced. ")
print(time_h, "hour(s)", time_m, "minute(s)", time_s, "second(s) is taken. ")
print("Leftover amount is ", leftovers_kg, "kg. You can purchase the leftover by giving ", cost, " TL.", sep="")