# -*- coding: utf-8 -*-
"""IF100 - THE5 - Alternative.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bHWnDwsNck7-16-N8WwQQJORpA-JfqlC
"""

f = open("songs.txt")
info = f.readlines()
f.close()

names_info = {}

for i in info:
  info[info.index(i)] = i.strip(" ,*, \n")

for i in range(len(info)):
  info[i] = info[i].split(" | ")
  name = info[i][0]
  info[i].pop(0)
  names_info[name] = info[i]


user_genre = input("Please enter the genre that you want to listen: ")


while True:

  if user_genre == "quit":
    print("The program is closed.")
    break


  wantedsongs = []
  last_pop = 0
  last_bpm = 0
  genrecontrol = False
  wantedname = []
  bestname = []
  for key, value in names_info.items():
    if value[0] == user_genre:
      genrecontrol = True
      wantedsongs.append(key)

  if genrecontrol == True:
    for i in wantedsongs:
      if int(names_info[i][1]) > last_pop:
        wantedname = [i]
        last_pop = int(names_info[i][1])
      if int(names_info[i][1]) == last_pop:
        wantedname.append(i)
  
    if len(wantedname) != 1:
      for j in wantedname:
        if int(names_info[j][2]) > last_bpm:
          bestname = j
          last_bpm = int(names_info[j][2])
  
    else:
      bestname = wantedname[0]
    print("You can listen", bestname, "that has", last_pop, "popularity and", last_bpm, "beats per minute.")

  else:
    print("There is no such genre " + user_genre + ".")

  user_genre = input("Please enter the genre that you want to listen: ")