# -*- coding: utf-8 -*-
"""IF100 - THE4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u2cypPfbFklFJEDPLbSQwdp2OZJHlkCq
"""

# Add your functions into this and the previous empty cell(s)
def choose_side():
  while True:
    chosen_side = input("Player1, please choose your side (either X or O): ")
    if chosen_side.isalpha():
      if ord(chosen_side) == 88 or  ord(chosen_side) == 79:
        return chosen_side

def display_enviroment(field):
  counter = 0
  for elem in field:
    if counter != 2:
      print(str(elem[0]) + "|" + str(elem[1]) + "|" + str(elem[2]))
      print("-+-+-")
      counter += 1
    else:
      print(str(elem[0]) + "|" + str(elem[1]) + "|" + str(elem[2]))

def makechoice(player):
  choice = input("Player" + player + ", please make your choice: ")
  return choice.split(",")

def implychoices(field, player_choice, player):
  rownum = int(player_choice[0])
  colnum = int(player_choice[1])
  if field[rownum][colnum] == " ":
    field[rownum][colnum] = player
    return field
  else:
    mark = field[rownum][colnum]
    print(mark + " is already in the location " + str(rownum) + "," + str(colnum) + ". Skipping this turn.")
    return field

def checkboard(field):
  count = 0
  for elem in field:
    for i in elem:
      if i != " ":
        count += 1
  if count == 9:
    return False
  else:
    return True

def is_winner(field):
  a = " "
  check = False
  if field[0][0] == field[1][1] == field[2][2]:
    mark = field[0][0]
    check = True
  elif field[0][2] == field[1][1] == field[2][0]:
    mark = field[0][2]
    check = True
  elif field[1][1] == field[1][0] == field[1][2]:
    mark = field[1][1]
    check = True
  elif field[1][1] == field[0][1] == field[0][2]:
    mark = field[1][1]
    check = True
  elif field[0][0] == field[0][1] == field[0][2]:
    mark = field[0][0]
    check = True
  elif field[0][0] == field[1][0] == field[2][0]:
    mark = field[0][0]
    check = True
  elif field[2][2] == field[1][2] == field[0][2]:
    mark = field[2][2]
    check = True
  elif field[2][2] == field[2][1] == field[2][0]:
    mark = field[2][2]
    check = True
  
  if check:
    return mark
  return a

# Main starts here
# DO NOT CHANGE ANY SINGLE PART AFTER THIS LINE

print("Welcome to the Tic-Tac-Toe Game!")
player1 = choose_side()
if player1 == "X":
  player2 = "O"
else:
  player2 = "X"

field = [[" ", " ", " "], [" ", " ", " "], [" ", " ", " "]]
display_enviroment(field)

while True:
  player1_choice = makechoice("1")
  field = implychoices(field, player1_choice, player1)
  display_enviroment(field)
  if is_winner(field) == player1 or checkboard(field) == False:
    break
  
  player2_choice = makechoice("2")
  field = implychoices(field, player2_choice, player2)
  display_enviroment(field)
  if is_winner(field) == player2 or checkboard(field) == False:
    break

if checkboard(field) == False:
  print("The game is finished! It is a tie.")

else:
  if player1 == is_winner(field):
    print("Player1 has won the game!")

  else:
    print("Player2 has won the game!")